- hosts: all
  become: true
  tasks: 
     - name: delete old deployment
       command: kubectl delete -f /Users/fuzail/.jenkins/workspace/pipeline/Deployment.yml
     - name: delete old service
       command: kubectl delete -f /Users/fuzail/.jenkins/workspace/pipeline/Service.yml
     - name: create new deployment
       command: kubectl apply -f /Users/fuzail/.jenkins/workspace/pipeline/Deployment.yml
     - name: create new service
       command: kubectl apply -f /Users/fuzail/.jenkins/workspace/pipeline/Service.yml
